model:
  name: potential_model
  params:
    e_dress:
      1: -62.66394777972123
      6: -35.80797015984071
      8: -26.85597761988052
    log_e_per_atom: true
    no_force_comp: 20
    separate_errors: true
    use_force: true
model_dir: ./force_16
network:
  name: PiNet
  params:
    atom_types:
    - 1
    - 6
    - 8
    basis_type: gaussian
    depth: 4
    ii_nodes:
    - 16
    - 16
    n_basis: 15
    pi_nodes:
    - 16
    pp_nodes:
    - 16
    - 16
    rc: 4.5
optimizer:
  class_name: Adam
  config:
    global_clipnorm: 0.01
    learning_rate:
      class_name: ExponentialDecay
      config:
        decay_rate: 0.994
        decay_steps: 10000
        initial_learning_rate: 0.0003
